-- tools/generate_options_doc.lua
-- Référence des réglages, tirée de la fenêtre d'options elle-même : jamais en retard sur le code.
--   lua tools/generate_options_doc.lua [frFR|enUS] > docs/options.md   (depuis la racine du dépôt)
-- Charge l'addon hors du jeu (mêmes simulations que tests/run_tests.lua), écoute chaque widget
-- posé par les pages puis écrit une page Markdown : page > onglet > section > réglage, avec son
-- type, sa valeur par défaut (profil neuf), ses bornes et son infobulle.

unpack = unpack or table.unpack
package.path = "tests/?.lua;" .. package.path
require("wow_mock")

Mock.locale = arg[1] or "frFR"

local NS = {}
local entriesByLayout = setmetatable({}, { __mode = "k" })

--- Enregistre chaque appel de widget d'un layout, dans l'ordre de la page.
local function ListenToLayouts()
    local Layout = getmetatable(NS.Widgets.NewLayout(CreateFrame("Frame")))
    local function record(layout, entry)
        local list = entriesByLayout[layout] or {}
        entriesByLayout[layout] = list
        entry.tab = layout.currentTab and layout.tabs[layout.currentTab].label
        list[#list + 1] = entry
        return entry
    end
    local function wrap(method, describe)
        local original = Layout[method]
        Layout[method] = function(self, ...)
            local result = original(self, ...)
            local entry = describe(...)
            if entry then
                entry.kind = entry.kind or method
                self.lastDocEntry = record(self, entry)
            end
            return result
        end
    end
    wrap("Title", function(text) return { text = text } end)
    wrap("Note", function(text, indent) return { text = text, indent = indent } end)
    wrap("Check", function(label, get, _, indent) return { text = label, get = get, indent = indent } end)
    wrap("Slider", function(label, minValue, maxValue, step, get, _, indent, format)
        return { text = label, get = get, indent = indent, min = minValue, max = maxValue, step = step, format = format }
    end)
    wrap("Dropdown", function(label, choices, get, _, indent)
        return { text = label, choices = choices, get = get, indent = indent }
    end)
    wrap("Color", function(label, get, _, indent) return { text = label, get = get, indent = indent } end)
    wrap("Button", function(label, _, indent) return { text = label, indent = indent } end)
    wrap("EditBox", function(label, _, _, _, indent) return { text = label, indent = indent } end)
    -- L'infobulle se rattache au dernier widget posé.
    local hint = Layout.Hint
    Layout.Hint = function(self, text)
        if self.lastDocEntry and text then self.lastDocEntry.hint = text end
        return hint(self, text)
    end
end

for raw in io.lines("AeonUI.toc") do
    local line = raw:gsub("\r", ""):gsub("%s+$", "")
    if line:match("%.lua$") then
        assert(loadfile((line:gsub("\\", "/"))))("AeonUI", NS)
        if NS.Widgets and not NS.docListening then NS.docListening = true ListenToLayouts() end
    end
end
Mock.FireEvent("ADDON_LOADED", "AeonUI")
Mock.FireEvent("PLAYER_LOGIN")
Mock.FireEvent("PLAYER_ENTERING_WORLD")

--------------------------------------------------------------------------------
-- Écriture
--------------------------------------------------------------------------------

local L = NS.L
local french = NS.activeLocale == "frFR"
local WORDS = french
    and { Check = "case", Slider = "curseur", Dropdown = "liste", Color = "couleur", Button = "bouton",
          EditBox = "zone de texte", default = "défaut", step = "pas", on = "cochée", off = "décochée", pages = "Pages",
          title = "Référence des réglages", intro = "Généré par `tools/generate_options_doc.lua` depuis la fenêtre d'options (`/aeon`). Valeurs par défaut d'un profil neuf." }
    or  { Check = "checkbox", Slider = "slider", Dropdown = "dropdown", Color = "color", Button = "button",
          EditBox = "text box", default = "default", step = "step", on = "on", off = "off", pages = "Pages",
          title = "Settings reference", intro = "Generated by `tools/generate_options_doc.lua` from the options window (`/aeon`). Defaults of a fresh profile." }

--- Texte sans codes de couleur WoW ni retours à la ligne.
local function Clean(text)
    return (tostring(text or ""):gsub("|c%x%x%x%x%x%x%x%x", ""):gsub("|r", ""):gsub("\n+", " "))
end

local function Anchor(text)
    return (Clean(text):lower():gsub("É", "é"):gsub("[^%w%s%-\128-\255]", ""):gsub("%s", "-"))
end

local function Default(entry)
    if not entry.get then return nil end
    local ok, value = pcall(entry.get)
    if not ok or value == nil then return nil end
    if entry.kind == "Check" then return value and WORDS.on or WORDS.off end
    if entry.kind == "Color" then
        return string.format("#%02X%02X%02X", (value.r or 0) * 255, (value.g or 0) * 255, (value.b or 0) * 255)
    end
    if entry.kind == "Dropdown" then
        local choices = type(entry.choices) == "function" and entry.choices() or entry.choices or {}
        for _, choice in ipairs(choices) do
            if choice.value == value then return Clean(choice.name) end
        end
    end
    if entry.kind == "Slider" then return string.format(entry.format or "%g", value) end
    return tostring(value)
end

local function Describe(entry)
    local parts = { WORDS[entry.kind] }
    local default = Default(entry)
    if default and default ~= "" then parts[#parts + 1] = WORDS.default .. " **" .. default .. "**" end
    if entry.kind == "Slider" then
        parts[#parts + 1] = string.format("%g – %g, " .. WORDS.step .. " %g", entry.min, entry.max, entry.step)
    end
    local line = "**" .. Clean(entry.text) .. "** — " .. table.concat(parts, ", ")
    if entry.hint then line = line .. "  \n  _" .. Clean(entry.hint) .. "_" end
    return line
end

local out = {}
local function write(line) out[#out + 1] = line or "" end

local Window, Options = NS.OptionsWindow, NS.Options
write("# AeonUI — " .. WORDS.title)
write()
write(WORDS.intro)
write()
write("## " .. WORDS.pages)
write()
for _, key in ipairs(Window.order) do
    local title = Clean(Window.pages[key].title)
    write("- [" .. title .. "](#" .. Anchor(title) .. ")")
end

for _, key in ipairs(Window.order) do
    write()
    write("## " .. Clean(Window.pages[key].title))
    local tab, inList = nil, false
    for index, entry in ipairs(entriesByLayout[Options:GetLayout(key)] or {}) do
        if entry.tab ~= tab then
            tab, inList = entry.tab, false
            write()
            write("### " .. Clean(tab))
        end
        if entry.kind == "Title" then
            inList = false
            write()
            write((tab and "#### " or "### ") .. Clean(entry.text))
        elseif entry.kind == "Note" then
            inList = false
            write()
            -- La première note est la description de la page ; les suivantes, des remarques.
            write(index == 1 and Clean(entry.text) or ("> " .. Clean(entry.text)))
        else
            if not inList then write() inList = true end
            local level = math.max(0, math.floor((entry.indent or 0) / 20) - 1)
            write(string.rep("  ", level) .. "- " .. Describe(entry))
        end
    end
end
write()
io.write(table.concat(out, "\n"))
